### ISSUE TITLE
 AutoML: Checking API activity in the wrong project

### ISSUE THREAD

**Issue by RomashkoVictor** [googleapis/java-automl#848]
Hello.

We have 4 projects: **dev**, **preprod**, **prod** and **infra**.
In the **dev** project is our business application written on Java, in the **infra** project we deployed autoML and other projects will use it with theirs credentials.
This library makes call to our dev environment and check is AutoML API is enabled. If not, we have error, but we call automl in different project.
We think that the project for this request comes from Credentials, not from actual request. If we enable AutoMl API - all works.
#### Environment details

1. Java version: 15
2. automl version(s): 1.2.3, 2.0.0

#### Steps to reproduce

  1. Create two projects. 
  2. In project one deploy AutoML.
  3. In project two create service account and add permissions to predict for AutoML in project one. Deploy some business service, that will call AutoML.

#### Stack trace
```
io.grpc.StatusRuntimeException: PERMISSION_DENIED: Cloud AutoML API has not been used in project XXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/automl.googleapis.com/overview?project=XXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:616)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:802)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:781)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

Thanks!

**Comment by morgandu** [comment]
Hi @RomashkoVictor , this is expected behavior. For the project that you don't deploy automl but will need to predict on automl model, you will still need to enable automl, because the prediction request is hitting automl service.

**Comment by RomashkoVictor** [comment]
Hi @morgandu.
Am I correct that when we create prediction request to the project(project 1) with credentials from another project(project 2), prediction request send to automl service that is located in project 2?
